// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiwxsqcposddikfhgzxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpd3hzcWNwb3NkZGlrZmhnenhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTM0NDUsImV4cCI6MjA2MzI2OTQ0NX0.776Lg7Z4heFhgE-_mR_N7xR77yg-ylFLWz2QYTq48UQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);